apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  namespace: process-thread
  labels:
    app: python-server
    language: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
        language: python
    spec:
      containers:
        - name: python-server
          image: pt-python:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: HEAVY_CALC_N
              value: "38"
            - name: UVICORN_WORKERS
              value: "1"
          resources:
            requests:
              cpu: "1"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
