apiVersion: v1
kind: Service
metadata:
  name: python-server
  namespace: process-thread
spec:
  type: ClusterIP
  selector:
    app: python-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
