apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: process-thread
  labels:
    app: go-server
    language: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
        language: go
    spec:
      containers:
        - name: go-server
          image: pt-go:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: HEAVY_CALC_N
              value: "43"
          resources:
            requests:
              cpu: "1"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
