apiVersion: apps/v1
kind: Deployment
metadata: { name: api, labels: { app: api } }
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - name: api
        image: localhost:5001/demo-api:v1
        ports: [{ containerPort: 8080 }]
        env:
        - name: APP_VERSION
          valueFrom: { configMapKeyRef: { name: api-config, key: version } }
        - name: RUNTIME
          valueFrom: { configMapKeyRef: { name: api-config, key: runtime } }
        readinessProbe: { httpGet: { path: /healthz, port: 8080 }, periodSeconds: 2 }
