apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd-app
resources:
  - namespace.yaml
  - ../../base
  - serviceprofile.yaml
  - trafficsplit.yaml
  - services-versioned.yaml
