apiVersion: v1
kind: Service
metadata:
  name: ts-server
  namespace: process-thread
spec:
  type: ClusterIP
  selector:
    app: ts-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
