apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-actix-server
  namespace: process-thread
  labels:
    app: rust-actix-server
    language: rust-actix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-actix-server
  template:
    metadata:
      labels:
        app: rust-actix-server
        language: rust-actix
    spec:
      containers:
        - name: rust-actix-server
          image: pt-rust-actix:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: HEAVY_CALC_N
              value: "43"
            - name: ACTIX_WORKERS
              value: "1"
          resources:
            requests:
              cpu: "1"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
