apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata: { name: demo, namespace: flux-system }
spec:
  interval: 1m
  url: https://github.com/tanaka-yui/learning.git
  ref: { branch: main }
