apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata: { name: generic-webhook, namespace: flux-system }
spec:
  type: generic
  address: http://echo-server.default.svc.cluster.local:8080/flux
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata: { name: demo-alert, namespace: flux-system }
spec:
  providerRef: { name: generic-webhook }
  eventSeverity: info
  eventSources:
  - { kind: Kustomization, name: demo-dev }
