apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-stg
namePrefix: stg-
resources: [../../base]
components: [../../components/metrics]
configMapGenerator:
- name: api-config
  behavior: merge
  literals: [version=v1-stg]
replicas:
- name: api
  count: 2
