apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-stg
resources: [../../base]
patches:
- path: patch-image.yaml
  target: { kind: Deployment, name: api }
configMapGenerator:
- name: api-config
  behavior: merge
  literals: [version=v1-stg, runtime=k8s]
