apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev
namePrefix: dev-
resources: [../../base]
components: [../../components/metrics]
configMapGenerator:
- name: api-config
  behavior: merge
  literals: [version=v1-dev]
