apiVersion: v1
kind: Service
metadata:
  name: java-server
  namespace: process-thread
spec:
  type: ClusterIP
  selector:
    app: java-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
